# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72dbe4cf36c4f9a57628a94b91bd7be1e6bf9bea34865aee68c6f58011972fad46d29d01a7e7ad18dcb691955ce7e845787bafbfe23025af049ab4c0521af49d

test:
  secret_key_base: ae960de29c36adb2d410d4b5edb5590dd046db520b6de9dc88a7f74496416901c7cd5b57c97d8b0378aab89f24a364d0797f1d44a7099f3abcd043121f968da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
